# HTTP -> HTTPS редирект для site.local
server {
    listen 80;
    server_name site.local;
    return 301 https://$host$request_uri;
}

# WordPress по HTTPS
server {
    listen 443 ssl;
    server_name site.local;

    ssl_certificate     /etc/nginx/ssl/site.crt;
    ssl_certificate_key /etc/nginx/ssl/site.key;

    # Защита wp-admin и wp-login.php по IP
    location ~* ^/(wp-admin|wp-login\.php) {
        allow 127.0.0.1;
        allow 95.174.107.182;
        deny all;

        proxy_pass http://wordpress:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        proxy_pass http://wordpress:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# Grafana для metrics.local
server {
    listen 80;
    server_name metrics.local;

    location / {
        proxy_pass http://grafana:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
